"""
"""
from __future__ import annotations
import pyridescence.glk
__all__: list[str] = ['bunny', 'cone', 'coordinate_system', 'cube', 'frustum', 'icosahedron', 'sphere', 'wire_bunny', 'wire_cone', 'wire_cube', 'wire_frustum', 'wire_icosahedron', 'wire_sphere']
def bunny() -> pyridescence.glk.Drawable:
    ...
def cone() -> pyridescence.glk.Drawable:
    ...
def coordinate_system() -> pyridescence.glk.Drawable:
    ...
def cube() -> pyridescence.glk.Drawable:
    ...
def frustum() -> pyridescence.glk.Drawable:
    ...
def icosahedron() -> pyridescence.glk.Drawable:
    ...
def sphere() -> pyridescence.glk.Drawable:
    ...
def wire_bunny() -> pyridescence.glk.Drawable:
    ...
def wire_cone() -> pyridescence.glk.Drawable:
    ...
def wire_cube() -> pyridescence.glk.Drawable:
    ...
def wire_frustum() -> pyridescence.glk.Drawable:
    ...
def wire_icosahedron() -> pyridescence.glk.Drawable:
    ...
def wire_sphere() -> pyridescence.glk.Drawable:
    ...
