"""
"""
from __future__ import annotations
import numpy
import pyridescence.glk
import typing
__all__: list[str] = ['ButtonFlags_MouseButtonLeft', 'ButtonFlags_MouseButtonMiddle', 'ButtonFlags_MouseButtonRight', 'ButtonFlags_None', 'ColorEditFlags_AlphaBar', 'ColorEditFlags_AlphaPreview', 'ColorEditFlags_AlphaPreviewHalf', 'ColorEditFlags_DisplayHSV', 'ColorEditFlags_DisplayHex', 'ColorEditFlags_DisplayRGB', 'ColorEditFlags_Float', 'ColorEditFlags_HDR', 'ColorEditFlags_InputHSV', 'ColorEditFlags_InputRGB', 'ColorEditFlags_NoAlpha', 'ColorEditFlags_NoBorder', 'ColorEditFlags_NoDragDrop', 'ColorEditFlags_NoInputs', 'ColorEditFlags_NoLabel', 'ColorEditFlags_NoOptions', 'ColorEditFlags_NoPicker', 'ColorEditFlags_NoSidePreview', 'ColorEditFlags_NoSmallPreview', 'ColorEditFlags_NoTooltip', 'ColorEditFlags_None', 'ColorEditFlags_PickerHueBar', 'ColorEditFlags_PickerHueWheel', 'ColorEditFlags_Uint8', 'Cond_Always', 'Cond_Appearing', 'Cond_FirstUseEver', 'Cond_Once', 'Dir_Down', 'Dir_Left', 'Dir_None', 'Dir_Right', 'Dir_Up', 'DockNodeFlags_AutoHideTabBar', 'DockNodeFlags_KeepAliveOnly', 'DockNodeFlags_NoDockingInCentralNode', 'DockNodeFlags_NoResize', 'DockNodeFlags_NoSplit', 'DockNodeFlags_None', 'DockNodeFlags_PassthruCentralNode', 'IM_COL32', 'IO', 'ImDrawList', 'ImVec2', 'ImVec4', 'MouseButton_Left', 'MouseButton_Middle', 'MouseButton_Right', 'Style', 'TableFlags_Borders', 'TableFlags_BordersH', 'TableFlags_BordersInner', 'TableFlags_BordersInnerH', 'TableFlags_BordersInnerV', 'TableFlags_BordersOuter', 'TableFlags_BordersOuterH', 'TableFlags_BordersOuterV', 'TableFlags_BordersV', 'TableFlags_ContextMenuInBody', 'TableFlags_Hideable', 'TableFlags_NoBordersInBody', 'TableFlags_NoBordersInBodyUntilResize', 'TableFlags_NoClip', 'TableFlags_NoHostExtendX', 'TableFlags_NoHostExtendY', 'TableFlags_NoKeepColumnsVisible', 'TableFlags_NoPadInnerX', 'TableFlags_NoPadOuterX', 'TableFlags_NoSavedSettings', 'TableFlags_None', 'TableFlags_PadOuterX', 'TableFlags_PreciseWidths', 'TableFlags_Reorderable', 'TableFlags_Resizable', 'TableFlags_RowBg', 'TableFlags_ScrollX', 'TableFlags_ScrollY', 'TableFlags_SizingFixedFit', 'TableFlags_SizingFixedSame', 'TableFlags_SizingMask_', 'TableFlags_SizingStretchProp', 'TableFlags_SizingStretchSame', 'TableFlags_SortMulti', 'TableFlags_SortTristate', 'TableFlags_Sortable', 'WindowFlags_AlwaysAutoResize', 'WindowFlags_NoBackground', 'WindowFlags_NoMove', 'WindowFlags_NoResize', 'WindowFlags_NoScrollbar', 'WindowFlags_NoTitleBar', 'WindowFlags_None', 'align_text_to_frame_padding', 'arrow_button', 'begin', 'begin_child', 'begin_combo', 'begin_group', 'begin_main_menu_bar', 'begin_menu', 'begin_menu_bar', 'begin_popup', 'begin_popup_modal', 'begin_tab_bar', 'begin_tab_item', 'begin_table', 'begin_tooltip', 'bullet', 'bullet_text', 'button', 'calc_item_width', 'calc_text_size', 'checkbox', 'checkbox_flags', 'close_current_popup', 'collapsing_header', 'collapsing_header_bool', 'color_button', 'color_edit3', 'color_edit4', 'color_picker3', 'color_picker4', 'combo', 'dock_builder_add_node', 'dock_builder_dock_window', 'dock_builder_finish', 'dock_builder_remove_node', 'dock_builder_split_node', 'dockspace', 'dockspace_over_viewport', 'drag_float', 'drag_float2', 'drag_float3', 'drag_float4', 'drag_float_range2', 'drag_int', 'drag_int2', 'drag_int3', 'drag_int4', 'drag_int_range2', 'dummy', 'end', 'end_child', 'end_combo', 'end_group', 'end_main_menu_bar', 'end_menu', 'end_menu_bar', 'end_popup', 'end_tab_bar', 'end_tab_item', 'end_table', 'end_tooltip', 'get_background_draw_list', 'get_clipboard_text', 'get_content_region_avail', 'get_content_region_max', 'get_cursor_pos', 'get_cursor_pos_x', 'get_cursor_pos_y', 'get_cursor_screen_pos', 'get_foreground_draw_list', 'get_frame_count', 'get_frame_height', 'get_frame_height_with_spacing', 'get_id', 'get_io', 'get_item_id', 'get_item_rect_max', 'get_item_rect_min', 'get_item_rect_size', 'get_key_name', 'get_key_pressed_amount', 'get_mouse_clicked_count', 'get_mouse_drag_delta', 'get_mouse_pos', 'get_mouse_pos_on_opening_current_popup', 'get_style', 'get_text_line_height', 'get_text_line_height_with_spacing', 'get_time', 'get_tree_node_to_label_spacing', 'get_version', 'get_window_content_region_max', 'get_window_content_region_min', 'get_window_draw_list', 'get_window_height', 'get_window_pos', 'get_window_size', 'get_window_width', 'image', 'image_button', 'indent', 'input_double', 'input_float', 'input_float2', 'input_float3', 'input_float4', 'input_int', 'input_int2', 'input_int3', 'input_int4', 'input_text', 'input_text_multiline', 'input_text_with_hint', 'invisible_button', 'is_any_item_active', 'is_any_item_focused', 'is_any_item_hovered', 'is_any_mouse_down', 'is_item_activated', 'is_item_active', 'is_item_clicked', 'is_item_deactivated', 'is_item_deactivated_after_edit', 'is_item_edited', 'is_item_focused', 'is_item_hovered', 'is_item_toggled_open', 'is_item_visible', 'is_key_down', 'is_key_pressed', 'is_key_released', 'is_mouse_clicked', 'is_mouse_double_clicked', 'is_mouse_down', 'is_mouse_dragging', 'is_mouse_hovering_rect', 'is_mouse_pos_valid', 'is_mouse_released', 'is_popup_open', 'is_rect_visible', 'is_rect_visible_pos_size', 'is_window_appearing', 'is_window_collapsed', 'is_window_focused', 'is_window_hovered', 'label_text', 'menu_item', 'newline', 'open_popup', 'open_popup_on_item_click', 'pop_button_repeat', 'pop_id', 'pop_item_width', 'pop_text_wrap_pos', 'progress_bar', 'push_button_repeat', 'push_id', 'push_item_width', 'push_text_wrap_pos', 'radio_button', 'radio_button_int', 'reset_mouse_drag_delta', 'same_line', 'selectable', 'separator', 'set_clipboard_text', 'set_cursor_pos', 'set_cursor_pos_x', 'set_cursor_pos_y', 'set_cursor_screen_pos', 'set_item_allow_overlap', 'set_item_default_focus', 'set_keyboard_focus_here', 'set_next_item_open', 'set_next_item_width', 'set_next_window_bg_alpha', 'set_next_window_collapsed', 'set_next_window_content_size', 'set_next_window_dock_id', 'set_next_window_focus', 'set_next_window_pos', 'set_next_window_scroll', 'set_next_window_size', 'set_next_window_size_constraints', 'set_tab_item_closed', 'set_tooltip', 'set_window_collapsed', 'set_window_focus', 'set_window_font_scale', 'set_window_pos', 'set_window_size', 'show_debug_log_window', 'show_demo_window', 'show_font_selector', 'show_metrics_window', 'show_style_editor', 'show_style_selector', 'slider_angle', 'slider_float', 'slider_float2', 'slider_float3', 'slider_float4', 'slider_int', 'slider_int2', 'slider_int3', 'slider_int4', 'small_button', 'spacing', 'style_colors_classic', 'style_colors_dark', 'style_colors_light', 'tab_item_button', 'table_header', 'table_headers_row', 'table_next_column', 'table_next_row', 'table_set_column_index', 'table_setup_column', 'table_setup_scroll_freeze', 'text', 'text_colored', 'text_disabled', 'text_unformatted', 'text_wrapped', 'tree_node', 'tree_pop', 'tree_push_str', 'unindent']
class IO:
    @property
    def delta_time(self) -> float:
        ...
    @property
    def framerate(self) -> float:
        ...
    @property
    def key_alt(self) -> bool:
        ...
    @property
    def key_ctrl(self) -> bool:
        ...
    @property
    def key_shift(self) -> bool:
        ...
    @property
    def key_super(self) -> bool:
        ...
    @property
    def keys_down(self) -> numpy.ndarray:
        ...
    @property
    def mouse_clicked(self) -> numpy.ndarray:
        ...
    @property
    def mouse_down(self) -> numpy.ndarray:
        ...
    @property
    def mouse_pos(self) -> numpy.ndarray:
        ...
    @property
    def mouse_wheel(self) -> float:
        ...
    @property
    def mouse_wheel_h(self) -> float:
        ...
    @property
    def nav_inputs(self) -> numpy.ndarray:
        ...
    @property
    def want_capture_keyboard(self) -> bool:
        ...
    @property
    def want_capture_mouse(self) -> bool:
        ...
class ImDrawList:
    def add_circle(self, center: numpy.ndarray[numpy.int32[2, 1]], radius: float, color: int, num_segments: int = 0, thickness: float = 1.0) -> None:
        ...
    def add_circle_filled(self, center: numpy.ndarray[numpy.int32[2, 1]], radius: float, color: int, num_segments: int = 0) -> None:
        ...
    def add_line(self, p0: numpy.ndarray[numpy.int32[2, 1]], p1: numpy.ndarray[numpy.int32[2, 1]], col: int, thickness: float = 1.0) -> None:
        ...
    def add_rect(self, p0: numpy.ndarray[numpy.int32[2, 1]], p1: numpy.ndarray[numpy.int32[2, 1]], color: int, rounding: float = 0.0, flags: int = 0, thickness: float = 1.0) -> None:
        ...
    def add_rect_filled(self, p0: numpy.ndarray[numpy.int32[2, 1]], p1: numpy.ndarray[numpy.int32[2, 1]], color: int, rounding: float = 0.0, flags: int = 0) -> None:
        ...
    def add_text(self, pos: numpy.ndarray[numpy.int32[2, 1]], color: int, text: str) -> None:
        ...
class ImVec2:
    x: float
    y: float
    def __buffer__(self, flags):
        """
        Return a buffer object that exposes the underlying memory of the object.
        """
    @typing.overload
    def __init__(self, arg0: float, arg1: float) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float32]) -> None:
        ...
    def __release_buffer__(self, buffer):
        """
        Release the buffer object that exposes the underlying memory of the object.
        """
class ImVec4:
    w: float
    x: float
    y: float
    z: float
    def __buffer__(self, flags):
        """
        Return a buffer object that exposes the underlying memory of the object.
        """
    @typing.overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float32]) -> None:
        ...
    def __release_buffer__(self, buffer):
        """
        Release the buffer object that exposes the underlying memory of the object.
        """
class Style:
    alpha: float
    anti_aliased_fill: bool
    anti_aliased_lines: bool
    anti_aliased_lines_use_tex: bool
    button_text_align: ImVec2
    cell_padding: ImVec2
    child_border_size: float
    child_rounding: float
    circle_tessellation_max_error: float
    color_button_position: int
    columns_min_spacing: float
    curve_tessellation_tol: float
    disabled_alpha: float
    display_safe_area_padding: ImVec2
    display_window_padding: ImVec2
    frame_border_size: float
    frame_padding: ImVec2
    frame_rounding: float
    grab_min_size: float
    grab_rounding: float
    indent_spacing: float
    item_inner_spacing: ImVec2
    item_spacing: ImVec2
    mouse_cursor_scale: float
    popup_border_size: float
    popup_rounding: float
    scrollbar_rounding: float
    scrollbar_size: float
    selectable_text_align: ImVec2
    tab_border_size: float
    tab_min_width_for_close_button: float
    tab_rounding: float
    touch_extra_padding: ImVec2
    window_border_size: float
    window_menu_button_position: int
    window_min_size: ImVec2
    window_padding: ImVec2
    window_rounding: float
    window_title_align: ImVec2
    @property
    def colors(self) -> list:
        ...
def IM_COL32(r: int, g: int, b: int, a: int) -> int:
    ...
def align_text_to_frame_padding() -> None:
    ...
def arrow_button(id: str, dir: int) -> bool:
    ...
def begin(name: str, open: bool = True, flags: int = 0) -> tuple[bool, bool]:
    ...
def begin_child(str_id: str, size: numpy.ndarray[numpy.int32[2, 1]] = ..., border: bool = False, flags: int = 0) -> bool:
    ...
def begin_combo(label: str, preview_value: str, flags: int = 0) -> bool:
    ...
def begin_group() -> None:
    ...
def begin_main_menu_bar() -> bool:
    ...
def begin_menu(label: str, enabled: bool = True) -> bool:
    ...
def begin_menu_bar() -> bool:
    ...
def begin_popup(id: str, flags: int) -> bool:
    ...
def begin_popup_modal(name: str, flags: int = 0) -> bool:
    ...
def begin_tab_bar(id: str, flags: int = 0) -> bool:
    ...
def begin_tab_item(label: str) -> bool:
    ...
def begin_table(str_id: str, column_n: int, flags: int = 0, outer_size: ImVec2 = ..., inner_width: float = 0.0) -> bool:
    ...
def begin_tooltip() -> None:
    ...
def bullet() -> None:
    ...
def bullet_text(text: str) -> None:
    ...
def button(label: str, size: numpy.ndarray[numpy.int32[2, 1]] = ...) -> bool:
    ...
def calc_item_width() -> float:
    ...
def calc_text_size(text: str, wrap_width: float = -1.0, hide_text_after_double_hash: bool = False) -> numpy.ndarray[numpy.float32[2, 1]]:
    ...
def checkbox(label: str, v: bool) -> tuple[bool, bool]:
    ...
def checkbox_flags(label: str, flags: int, flags_value: int) -> tuple[bool, int]:
    ...
def close_current_popup() -> None:
    ...
def collapsing_header(label: str, flags: int = 0) -> bool:
    ...
def collapsing_header_bool(label: str, open: bool, flags: int = 0) -> tuple[bool, bool]:
    ...
def color_button(desc_id: str, color: numpy.ndarray[numpy.float32[4, 1]], flags: int = 0, size: numpy.ndarray[numpy.int32[2, 1]] = ...) -> bool:
    ...
def color_edit3(label: str, color: numpy.ndarray[numpy.float32[3, 1]], flags: int = 0) -> tuple[bool, numpy.ndarray[numpy.float32[3, 1]]]:
    ...
def color_edit4(label: str, color: numpy.ndarray[numpy.float32[4, 1]], flags: int = 0) -> tuple[bool, numpy.ndarray[numpy.float32[4, 1]]]:
    ...
def color_picker3(label: str, color: numpy.ndarray[numpy.float32[3, 1]], flags: int = 0) -> tuple[bool, numpy.ndarray[numpy.float32[3, 1]]]:
    ...
def color_picker4(label: str, color: numpy.ndarray[numpy.float32[4, 1]], flags: int = 0) -> tuple[bool, numpy.ndarray[numpy.float32[4, 1]]]:
    ...
def combo(label: str, current_item: int, items: list[str], popup_max_height_in_items: int = -1) -> tuple[bool, int]:
    ...
def dock_builder_add_node(node_id: int = 0, flags: int = 0) -> int:
    ...
def dock_builder_dock_window(window_name: str, node_id: int) -> None:
    ...
def dock_builder_finish(node_id: int) -> None:
    ...
def dock_builder_remove_node(node_id: int) -> None:
    ...
def dock_builder_split_node(node_id: int, split_dir: int, size_ratio_for_node_at_dir: float) -> tuple[int, int]:
    ...
def dockspace(id: int, size: numpy.ndarray[numpy.int32[2, 1]] = ..., flags: int = 0) -> int:
    ...
def dockspace_over_viewport(flags: int = 0) -> int:
    ...
def drag_float(label: str, v: float, v_speed: float = 1.0, v_min: float = 0.0, v_max: float = 0.0, format: str = '%.3f', power: float = 1.0) -> tuple[bool, float]:
    ...
def drag_float2(label: str, v: numpy.ndarray[numpy.float32[2, 1]], v_speed: float = 1.0, v_min: float = 0.0, v_max: float = 0.0, format: str = '%.3f', power: float = 1.0) -> tuple[bool, numpy.ndarray[numpy.float32[2, 1]]]:
    ...
def drag_float3(label: str, v: numpy.ndarray[numpy.float32[3, 1]], v_speed: float = 1.0, v_min: float = 0.0, v_max: float = 0.0, format: str = '%.3f', power: float = 1.0) -> tuple[bool, numpy.ndarray[numpy.float32[3, 1]]]:
    ...
def drag_float4(label: str, v: numpy.ndarray[numpy.float32[4, 1]], v_speed: float = 1.0, v_min: float = 0.0, v_max: float = 0.0, format: str = '%.3f', power: float = 1.0) -> tuple[bool, numpy.ndarray[numpy.float32[4, 1]]]:
    ...
def drag_float_range2(label: str, v: numpy.ndarray[numpy.float32[2, 1]], v_speed: float = 1.0, v_min: float = 0.0, v_max: float = 0.0, format: str = '%.3f', format_max: str = '%.3f', power: float = 1.0) -> tuple[bool, numpy.ndarray[numpy.float32[2, 1]]]:
    ...
def drag_int(label: str, v: int, v_speed: int = 1, v_min: int = 0, v_max: int = 0, format: str = '%d') -> tuple[bool, int]:
    ...
def drag_int2(label: str, v: numpy.ndarray[numpy.int32[2, 1]], v_speed: int = 1, v_min: int = 0, v_max: int = 0, format: str = '%d') -> tuple[bool, numpy.ndarray[numpy.int32[2, 1]]]:
    ...
def drag_int3(label: str, v: numpy.ndarray[numpy.int32[3, 1]], v_speed: int = 1, v_min: int = 0, v_max: int = 0, format: str = '%d') -> tuple[bool, numpy.ndarray[numpy.int32[3, 1]]]:
    ...
def drag_int4(label: str, v: numpy.ndarray[numpy.int32[4, 1]], v_speed: int = 1, v_min: int = 0, v_max: int = 0, format: str = '%d') -> tuple[bool, numpy.ndarray[numpy.int32[4, 1]]]:
    ...
def drag_int_range2(label: str, v: numpy.ndarray[numpy.int32[2, 1]], v_speed: int = 1, v_min: int = 0, v_max: int = 0, format: str = '%d', format_max: str = '%d') -> tuple[bool, numpy.ndarray[numpy.int32[2, 1]]]:
    ...
def dummy(size: numpy.ndarray[numpy.int32[2, 1]]) -> None:
    ...
def end() -> None:
    ...
def end_child() -> None:
    ...
def end_combo() -> None:
    ...
def end_group() -> None:
    ...
def end_main_menu_bar() -> None:
    ...
def end_menu() -> None:
    ...
def end_menu_bar() -> None:
    ...
def end_popup() -> None:
    ...
def end_tab_bar() -> None:
    ...
def end_tab_item() -> None:
    ...
def end_table() -> None:
    ...
def end_tooltip() -> None:
    ...
def get_background_draw_list() -> ImDrawList:
    ...
def get_clipboard_text() -> str:
    ...
def get_content_region_avail() -> numpy.ndarray[numpy.float32[2, 1]]:
    ...
def get_content_region_max() -> numpy.ndarray[numpy.float32[2, 1]]:
    ...
def get_cursor_pos() -> numpy.ndarray[numpy.float32[2, 1]]:
    ...
def get_cursor_pos_x() -> float:
    ...
def get_cursor_pos_y() -> float:
    ...
def get_cursor_screen_pos() -> numpy.ndarray[numpy.float32[2, 1]]:
    ...
def get_foreground_draw_list() -> ImDrawList:
    ...
def get_frame_count() -> int:
    ...
def get_frame_height() -> float:
    ...
def get_frame_height_with_spacing() -> float:
    ...
def get_id(name: str) -> int:
    ...
def get_io() -> IO:
    ...
def get_item_id() -> int:
    ...
def get_item_rect_max() -> numpy.ndarray[numpy.float32[2, 1]]:
    ...
def get_item_rect_min() -> numpy.ndarray[numpy.float32[2, 1]]:
    ...
def get_item_rect_size() -> numpy.ndarray[numpy.float32[2, 1]]:
    ...
def get_key_name(key_index: int) -> str:
    ...
def get_key_pressed_amount(key: ImGuiKey, repeat_delay: float = 0.0, repeat_rate: float = 0.0) -> int:
    ...
def get_mouse_clicked_count(button: int) -> int:
    ...
def get_mouse_drag_delta(button: int = 0, lock_threshold: float = -1.0) -> numpy.ndarray[numpy.float32[2, 1]]:
    ...
def get_mouse_pos() -> numpy.ndarray[numpy.float32[2, 1]]:
    ...
def get_mouse_pos_on_opening_current_popup() -> numpy.ndarray[numpy.float32[2, 1]]:
    ...
def get_style() -> Style:
    ...
def get_text_line_height() -> float:
    ...
def get_text_line_height_with_spacing() -> float:
    ...
def get_time() -> float:
    ...
def get_tree_node_to_label_spacing() -> float:
    ...
def get_version() -> str:
    ...
def get_window_content_region_max() -> numpy.ndarray[numpy.float32[2, 1]]:
    ...
def get_window_content_region_min() -> numpy.ndarray[numpy.float32[2, 1]]:
    ...
@typing.overload
def get_window_draw_list() -> ImDrawList:
    ...
@typing.overload
def get_window_draw_list() -> ImDrawList:
    ...
def get_window_height() -> float:
    ...
def get_window_pos() -> numpy.ndarray[numpy.int32[2, 1]]:
    ...
def get_window_size() -> numpy.ndarray[numpy.int32[2, 1]]:
    ...
def get_window_width() -> float:
    ...
def image(texture: pyridescence.glk.Texture, size: numpy.ndarray[numpy.int32[2, 1]], uv0: numpy.ndarray[numpy.float32[2, 1]] = ..., uv1: numpy.ndarray[numpy.float32[2, 1]] = ..., tint_col: numpy.ndarray[numpy.float32[4, 1]] = ..., border_col: numpy.ndarray[numpy.float32[4, 1]] = ...) -> None:
    ...
def image_button(str_id: str, texture: pyridescence.glk.Texture, size: numpy.ndarray[numpy.int32[2, 1]], uv0: numpy.ndarray[numpy.float32[2, 1]] = ..., uv1: numpy.ndarray[numpy.float32[2, 1]] = ..., bg_col: numpy.ndarray[numpy.float32[4, 1]] = ..., tint_col: numpy.ndarray[numpy.float32[4, 1]] = ...) -> bool:
    ...
def indent(indent_w: float = 0.0) -> None:
    ...
def input_double(label: str, v: float, step: float = 0.0, step_fast: float = 0.0, format: str = '%.6f', flags: int = 0) -> tuple[bool, float]:
    ...
def input_float(label: str, v: float, step: float = 0.0, step_fast: float = 0.0, format: str = '%.3f', flags: int = 0) -> tuple[bool, float]:
    ...
def input_float2(label: str, v: numpy.ndarray[numpy.float32[2, 1]], format: str = '%.3f', flags: int = 0) -> tuple[bool, numpy.ndarray[numpy.float32[2, 1]]]:
    ...
def input_float3(label: str, v: numpy.ndarray[numpy.float32[3, 1]], format: str = '%.3f', flags: int = 0) -> tuple[bool, numpy.ndarray[numpy.float32[3, 1]]]:
    ...
def input_float4(label: str, v: numpy.ndarray[numpy.float32[4, 1]], format: str = '%.3f', flags: int = 0) -> tuple[bool, numpy.ndarray[numpy.float32[4, 1]]]:
    ...
def input_int(label: str, v: int, step: int = 1, step_fast: int = 100, flags: int = 0) -> tuple[bool, int]:
    ...
def input_int2(label: str, v: numpy.ndarray[numpy.int32[2, 1]], flags: int = 0) -> tuple[bool, numpy.ndarray[numpy.int32[2, 1]]]:
    ...
def input_int3(label: str, v: numpy.ndarray[numpy.int32[3, 1]], flags: int = 0) -> tuple[bool, numpy.ndarray[numpy.int32[3, 1]]]:
    ...
def input_int4(label: str, v: numpy.ndarray[numpy.int32[4, 1]], flags: int = 0) -> tuple[bool, numpy.ndarray[numpy.int32[4, 1]]]:
    ...
def input_text(label: str, text: str, flags: int = 0, buffer_size: int = 256) -> tuple[bool, str]:
    ...
def input_text_multiline(label: str, text: str, size: numpy.ndarray[numpy.int32[2, 1]] = ..., flags: int = 0, buffer_size: int = 256) -> tuple[bool, str]:
    ...
def input_text_with_hint(label: str, hint: str, text: str, flags: int = 0, buffer_size: int = 256) -> tuple[bool, str]:
    ...
def invisible_button(id: str, size: numpy.ndarray[numpy.int32[2, 1]], flags: int = 0) -> bool:
    ...
def is_any_item_active() -> bool:
    ...
def is_any_item_focused() -> bool:
    ...
def is_any_item_hovered() -> bool:
    ...
def is_any_mouse_down() -> bool:
    ...
def is_item_activated() -> bool:
    ...
def is_item_active() -> bool:
    ...
def is_item_clicked(mouse_button: int = 0) -> bool:
    ...
def is_item_deactivated() -> bool:
    ...
def is_item_deactivated_after_edit() -> bool:
    ...
def is_item_edited() -> bool:
    ...
def is_item_focused() -> bool:
    ...
def is_item_hovered(flags: int = 0) -> bool:
    ...
def is_item_toggled_open() -> bool:
    ...
def is_item_visible() -> bool:
    ...
def is_key_down(key: int) -> bool:
    ...
def is_key_pressed(key: int, repeat: bool = False) -> bool:
    ...
def is_key_released(key: int) -> bool:
    ...
def is_mouse_clicked(button: int, repeat: bool = False) -> bool:
    ...
def is_mouse_double_clicked(button: int) -> bool:
    ...
def is_mouse_down(button: int) -> bool:
    ...
def is_mouse_dragging(button: int, lock_threshold: float = -1.0) -> bool:
    ...
def is_mouse_hovering_rect(r_min: numpy.ndarray[numpy.float32[2, 1]], r_max: numpy.ndarray[numpy.float32[2, 1]], clip: bool = True) -> bool:
    ...
def is_mouse_pos_valid(mouse_pos: numpy.ndarray[numpy.float32[2, 1]] = ...) -> bool:
    ...
def is_mouse_released(button: int) -> bool:
    ...
def is_popup_open(name: str, flags: int = 0) -> bool:
    ...
def is_rect_visible(arg0: numpy.ndarray[numpy.float32[2, 1]]) -> bool:
    ...
def is_rect_visible_pos_size(arg0: numpy.ndarray[numpy.float32[2, 1]], arg1: numpy.ndarray[numpy.float32[2, 1]]) -> bool:
    ...
def is_window_appearing() -> bool:
    ...
def is_window_collapsed() -> bool:
    ...
def is_window_focused(flags: int = 0) -> bool:
    ...
def is_window_hovered(flags: int = 0) -> bool:
    ...
def label_text(label: str, text: str) -> None:
    ...
def menu_item(label: str, shortcut: str = '', selected: bool = False, enabled: bool = True) -> bool:
    ...
def newline() -> None:
    ...
def open_popup(name: str) -> None:
    ...
def open_popup_on_item_click(str_id: str, mouse_button: int = 0) -> None:
    ...
def pop_button_repeat() -> None:
    ...
def pop_id() -> None:
    ...
def pop_item_width() -> None:
    ...
def pop_text_wrap_pos() -> None:
    ...
def progress_bar(fraction: float, size: numpy.ndarray[numpy.int32[2, 1]] = ..., overlay: str = '') -> None:
    ...
def push_button_repeat(repeat: bool) -> None:
    ...
def push_id(str_id: str) -> None:
    ...
def push_item_width(item_width: float) -> None:
    ...
def push_text_wrap_pos(wrap_local_pos_x: float = 0.0) -> None:
    ...
def radio_button(label: str, active: bool) -> bool:
    ...
def radio_button_int(label: str, v: int, v_button: int) -> tuple[bool, int]:
    ...
def reset_mouse_drag_delta(button: int = 0) -> None:
    ...
def same_line(offset_from_start_x: float = 0.0, spacing: float = -1.0) -> None:
    ...
def selectable(label: str, selected: bool = False, flags: int = 0, size: numpy.ndarray[numpy.int32[2, 1]] = ...) -> bool:
    ...
def separator() -> None:
    ...
def set_clipboard_text(text: str) -> None:
    ...
def set_cursor_pos(pos: numpy.ndarray[numpy.float32[2, 1]]) -> None:
    ...
def set_cursor_pos_x(x: float) -> None:
    ...
def set_cursor_pos_y(y: float) -> None:
    ...
def set_cursor_screen_pos(pos: numpy.ndarray[numpy.float32[2, 1]]) -> None:
    ...
def set_item_allow_overlap() -> None:
    ...
def set_item_default_focus() -> None:
    ...
def set_keyboard_focus_here(offset: int = 0) -> None:
    ...
def set_next_item_open(is_open: bool, cond: int = 0) -> None:
    ...
def set_next_item_width(item_width: float) -> None:
    ...
def set_next_window_bg_alpha(alpha: float) -> None:
    ...
def set_next_window_collapsed(collapsed: bool, cond: int = 0) -> None:
    ...
def set_next_window_content_size(size: numpy.ndarray[numpy.int32[2, 1]]) -> None:
    ...
def set_next_window_dock_id(dock_id: int, cond: int = 0) -> None:
    ...
def set_next_window_focus() -> None:
    ...
def set_next_window_pos(pos: numpy.ndarray[numpy.int32[2, 1]], cond: int = 0, pivot: numpy.ndarray[numpy.int32[2, 1]] = ...) -> None:
    ...
def set_next_window_scroll(scroll: numpy.ndarray[numpy.int32[2, 1]]) -> None:
    ...
def set_next_window_size(size: numpy.ndarray[numpy.int32[2, 1]], cond: int = 0) -> None:
    ...
def set_next_window_size_constraints(size_min: numpy.ndarray[numpy.int32[2, 1]], size_max: numpy.ndarray[numpy.int32[2, 1]]) -> None:
    ...
def set_tab_item_closed(tab_or_dockspace_id: str) -> None:
    ...
def set_tooltip(fmt: str) -> None:
    ...
@typing.overload
def set_window_collapsed(collapsed: bool, cond: int = 0) -> None:
    ...
@typing.overload
def set_window_collapsed(name: str, collapsed: bool, cond: int = 0) -> None:
    ...
@typing.overload
def set_window_focus() -> None:
    ...
@typing.overload
def set_window_focus(name: str) -> None:
    ...
def set_window_font_scale(scale: float) -> None:
    ...
@typing.overload
def set_window_pos(pos: numpy.ndarray[numpy.int32[2, 1]], cond: int = 0) -> None:
    ...
@typing.overload
def set_window_pos(name: str, pos: numpy.ndarray[numpy.int32[2, 1]], cond: int = 0) -> None:
    ...
@typing.overload
def set_window_size(size: numpy.ndarray[numpy.int32[2, 1]], cond: int = 0) -> None:
    ...
@typing.overload
def set_window_size(name: str, size: numpy.ndarray[numpy.int32[2, 1]], cond: int = 0) -> None:
    ...
def show_debug_log_window() -> None:
    ...
def show_demo_window() -> None:
    ...
def show_font_selector(label: str) -> None:
    ...
def show_metrics_window() -> None:
    ...
def show_style_editor() -> None:
    ...
def show_style_selector(label: str) -> None:
    ...
def slider_angle(label: str, v_rad: float, v_degrees_min: float = -360.0, v_degrees_max: float = 360.0, format: str = '%.0f deg', flags: int = 0) -> tuple[bool, float]:
    ...
def slider_float(label: str, v: float, v_min: float, v_max: float, format: str = '%.3f', power: float = 1.0) -> tuple[bool, float]:
    ...
def slider_float2(label: str, v: numpy.ndarray[numpy.float32[2, 1]], v_min: float, v_max: float, format: str = '%.3f', power: float = 1.0) -> tuple[bool, numpy.ndarray[numpy.float32[2, 1]]]:
    ...
def slider_float3(label: str, v: numpy.ndarray[numpy.float32[3, 1]], v_min: float, v_max: float, format: str = '%.3f', flags: int = 0) -> tuple[bool, numpy.ndarray[numpy.float32[3, 1]]]:
    ...
def slider_float4(label: str, v: numpy.ndarray[numpy.float32[4, 1]], v_min: float, v_max: float, format: str = '%.3f', flags: int = 0) -> tuple[bool, numpy.ndarray[numpy.float32[4, 1]]]:
    ...
def slider_int(label: str, v: int, v_min: int, v_max: int, format: str = '%d', flags: int = 0) -> tuple[bool, int]:
    ...
def slider_int2(label: str, v: numpy.ndarray[numpy.int32[2, 1]], v_min: int, v_max: int, format: str = '%d', flags: int = 0) -> tuple[bool, numpy.ndarray[numpy.int32[2, 1]]]:
    ...
def slider_int3(label: str, v: numpy.ndarray[numpy.int32[3, 1]], v_min: int, v_max: int, format: str = '%d', flags: int = 0) -> tuple[bool, numpy.ndarray[numpy.int32[3, 1]]]:
    ...
def slider_int4(label: str, v: numpy.ndarray[numpy.int32[4, 1]], v_min: int, v_max: int, format: str = '%d', flags: int = 0) -> tuple[bool, numpy.ndarray[numpy.int32[4, 1]]]:
    ...
def small_button(label: str) -> bool:
    ...
def spacing() -> None:
    ...
def style_colors_classic(dst: Style = None) -> None:
    ...
def style_colors_dark(dst: Style = None) -> None:
    ...
def style_colors_light(dst: Style = None) -> None:
    ...
def tab_item_button(label: str, flags: int = 0) -> bool:
    ...
def table_header(label: str) -> None:
    ...
def table_headers_row() -> None:
    ...
def table_next_column() -> bool:
    ...
def table_next_row(row_flags: int = 0, min_row_height: float = 0.0) -> None:
    ...
def table_set_column_index(column_index: int) -> bool:
    ...
def table_setup_column(label: str, flags: int = 0, init_width_or_weight: float = 0.0, user_id: int = 0) -> None:
    ...
def table_setup_scroll_freeze(cols: int, rows: int) -> None:
    ...
def text(text: str) -> None:
    ...
def text_colored(col: numpy.ndarray[numpy.float32[4, 1]], text: str) -> None:
    ...
def text_disabled(text: str) -> None:
    ...
def text_unformatted(text: str) -> None:
    ...
def text_wrapped(text: str) -> None:
    ...
def tree_node(label: str) -> bool:
    ...
def tree_pop() -> None:
    ...
def tree_push_str(str_id: str) -> None:
    ...
def unindent(indent_w: float = 0.0) -> None:
    ...
ButtonFlags_MouseButtonLeft: int = 1
ButtonFlags_MouseButtonMiddle: int = 4
ButtonFlags_MouseButtonRight: int = 2
ButtonFlags_None: int = 0
ColorEditFlags_AlphaBar: int = 2
ColorEditFlags_AlphaPreview: int = 2
ColorEditFlags_AlphaPreviewHalf: int = 2
ColorEditFlags_DisplayHSV: int = 2
ColorEditFlags_DisplayHex: int = 2
ColorEditFlags_DisplayRGB: int = 2
ColorEditFlags_Float: int = 2
ColorEditFlags_HDR: int = 2
ColorEditFlags_InputHSV: int = 2
ColorEditFlags_InputRGB: int = 2
ColorEditFlags_NoAlpha: int = 2
ColorEditFlags_NoBorder: int = 2
ColorEditFlags_NoDragDrop: int = 2
ColorEditFlags_NoInputs: int = 2
ColorEditFlags_NoLabel: int = 2
ColorEditFlags_NoOptions: int = 2
ColorEditFlags_NoPicker: int = 2
ColorEditFlags_NoSidePreview: int = 2
ColorEditFlags_NoSmallPreview: int = 2
ColorEditFlags_NoTooltip: int = 2
ColorEditFlags_None: int = 0
ColorEditFlags_PickerHueBar: int = 2
ColorEditFlags_PickerHueWheel: int = 2
ColorEditFlags_Uint8: int = 2
Cond_Always: int = 1
Cond_Appearing: int = 8
Cond_FirstUseEver: int = 4
Cond_Once: int = 2
Dir_Down: int = 3
Dir_Left: int = 0
Dir_None: int = -1
Dir_Right: int = 1
Dir_Up: int = 2
DockNodeFlags_AutoHideTabBar: int = 64
DockNodeFlags_KeepAliveOnly: int = 1
DockNodeFlags_NoDockingInCentralNode: int = 4
DockNodeFlags_NoResize: int = 32
DockNodeFlags_NoSplit: int = 16
DockNodeFlags_None: int = 0
DockNodeFlags_PassthruCentralNode: int = 8
MouseButton_Left: int = 0
MouseButton_Middle: int = 2
MouseButton_Right: int = 1
TableFlags_Borders: int = 1920
TableFlags_BordersH: int = 384
TableFlags_BordersInner: int = 640
TableFlags_BordersInnerH: int = 128
TableFlags_BordersInnerV: int = 512
TableFlags_BordersOuter: int = 1280
TableFlags_BordersOuterH: int = 256
TableFlags_BordersOuterV: int = 1024
TableFlags_BordersV: int = 1536
TableFlags_ContextMenuInBody: int = 32
TableFlags_Hideable: int = 4
TableFlags_NoBordersInBody: int = 2048
TableFlags_NoBordersInBodyUntilResize: int = 4096
TableFlags_NoClip: int = 1048576
TableFlags_NoHostExtendX: int = 65536
TableFlags_NoHostExtendY: int = 131072
TableFlags_NoKeepColumnsVisible: int = 262144
TableFlags_NoPadInnerX: int = 8388608
TableFlags_NoPadOuterX: int = 4194304
TableFlags_NoSavedSettings: int = 16
TableFlags_None: int = 0
TableFlags_PadOuterX: int = 2097152
TableFlags_PreciseWidths: int = 524288
TableFlags_Reorderable: int = 2
TableFlags_Resizable: int = 1
TableFlags_RowBg: int = 64
TableFlags_ScrollX: int = 16777216
TableFlags_ScrollY: int = 33554432
TableFlags_SizingFixedFit: int = 8192
TableFlags_SizingFixedSame: int = 16384
TableFlags_SizingMask_: int = 57344
TableFlags_SizingStretchProp: int = 24576
TableFlags_SizingStretchSame: int = 32768
TableFlags_SortMulti: int = 67108864
TableFlags_SortTristate: int = 134217728
TableFlags_Sortable: int = 8
WindowFlags_AlwaysAutoResize: int = 64
WindowFlags_NoBackground: int = 128
WindowFlags_NoMove: int = 4
WindowFlags_NoResize: int = 2
WindowFlags_NoScrollbar: int = 8
WindowFlags_NoTitleBar: int = 1
WindowFlags_None: int = 0
