name: Deb

on:
  push:
    branches: [ deb ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DISTRO: [
          { "ubuntu": "focal", "label": "ubuntu2004" },
          { "ubuntu": "jammy", "label": "ubuntu2204" },
          { "ubuntu": "noble", "label": "ubuntu2404" },
        ]
        PLATFORM: [ "linux/amd64", "linux/arm64" ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        continue-on-error: true
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          tags: iridescence:latest
          file: ${{github.workspace}}/docker/ubuntu/Dockerfile_deb
          build-args: |
            BASE_IMAGE=ubuntu:${{ matrix.DISTRO.ubuntu }}
          context: .
          platforms: ${{ matrix.PLATFORM }}
          push: false

      - name: Extract deb
        run: |
          docker run -v ${{github.workspace}}/${{ matrix.DISTRO.label }}:/output --platform=${{ matrix.PLATFORM }} iridescence:latest /bin/bash -c "cp /root/iridescence/build/*.deb /output/"

      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.DISTRO.label }}
          path: ${{github.workspace}}/${{ matrix.DISTRO.label }}

  ppa:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          repository: koide3/ppa
          path: ppa
          token: ${{ secrets.PPA_PAT }}

      - name: Download deb
        uses: actions/download-artifact@v4
        with:
          pattern: ubuntu*
          path: deb

      - name: Copy deb
        run: cp -R ${{github.workspace}}/deb/ubuntu* ${{github.workspace}}/ppa/

      - name: Push
        run: |
            git config --global user.name "k.koide"
            git config --global user.email "k.koide@aist.go.jp"
            cd ppa
            git add .
            git commit -m "${{ github.action_repository }}/${{ github.ref_name }}"
            git push origin main
